### ISSUE TITLE
Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by balazs-zsoldos** [BSI-Business-Systems-Integration-AG/eclipse-settings-maven-plugin#1]
If I add the plugin as it is in the documentation with the execution, eclipse gets red and it cannot find an m2e extension to solve that. Either the documentation should be fixed or something with the lifecycle mapping.

**Comment by jmini** [comment]
Thank you for this feedback.

> If I add the plugin as it is in the documentation with the execution

Can you be more precise? what documentation are you refering to?

If you follow the [2.2. Create a new Scout Project](http://eclipsescout.github.io/6.0/beginners-guide.html#sec-create_project_simple) from the beginner guide, you should get a Dialog "Discover m2e plugin connectors" that trigger an installation.

**Comment by balazs-zsoldos** [comment]
By documentation I meant the README file in the root of this project. I tried the "Discover m2e plugin connectors" but Eclipse did not find any. I solved the issue by specifying the lifecycle mapping in my pom.xml file as the following:

```
<pluginExecution>
	<pluginExecutionFilter>
		<groupId>
			org.eclipse.scout
		</groupId>
		<artifactId>
			eclipse-settings-maven-plugin
		</artifactId>
		<versionRange>
			[3.0.1,)
		</versionRange>
		<goals>
			<goal>
				eclipse-settings
			</goal>
		</goals>
	</pluginExecutionFilter>
	<action>
		<execute>
			<runOnIncremental>false</runOnIncremental>
		</execute>
	</action>
</pluginExecution>
```

**Comment by briandealwis** [comment]
I hit this problem as well.
