### ISSUE TITLE
Missing support of a "skip" parameter

### ISSUE THREAD

**Issue by mschaufelberger** [BSI-Business-Systems-Integration-AG/eclipse-settings-maven-plugin#3]
Currently it's not possible for a module to avoid the execution of the eclipse-settings-maven-plugin. Similar to other plugins, it should support a <skip> flag.

See also:
http://stackoverflow.com/questions/7821152/disable-a-maven-plugin-defined-in-a-parent-pom

**Comment by jmini** [comment]
I have tested your change. It looks good to me. Thank you!

---

I know the documentation of this project is not ideal...

But when a new configuration is added to the plugin, I think it should be mentioned at the end of the "Configure Eclipse Settings maven-plugin in your project" section of the `readme.markdown` File. Something like:

> #### Skipping the plugin execution
> 
> The plugin has a 'skip' configuration parameter, to block the configuration of a project. This can be usefull to disable a configuration made in the the parent pom at child pom level. Example:
```
       <plugin>
          <groupId>org.eclipse.scout</groupId>
          <artifactId>eclipse-settings-maven-plugin</artifactId>
          <configuration>
            <skip>true</skip>
          </configuration>
      </plugin>
```

@mschaufelberger: What do you think?

**Comment by mschaufelberger** [comment]
@jmini, you're perfectly right. Thank you for the hint and your proposal which I copied into the `readme.markdown` :innocent:
