### ISSUE TITLE
Release 3.0.3

### ISSUE THREAD

**Issue by briandealwis** [BSI-Business-Systems-Integration-AG/eclipse-settings-maven-plugin#6]
Would it be possible to publish 3.0.3 to pick up #5?  Thanks!

**Comment by padyx** [comment]
Release 3.0.3 was created and uploaded to Bintray.

Please check it out - your feedback (whether it works as expected) would be appreciated.

**Comment by briandealwis** [comment]
Does the trick for me!  Thanks!

**Comment by padyx** [comment]
You're welcome!

**Comment by jmini** [comment]
Thank you @padyx for the release.

For information, the bintray repo is here:
https://bintray.com/bsi-business-systems-integration-ag/scout-eclipse-org/eclipse-settings-maven-plugin

The former versions of this plugin were pushed to maven central, probably with the synchronisation possibilities offered by bintray.
See: https://mvnrepository.com/artifact/org.eclipse.scout/eclipse-settings-maven-plugin

Without the maven central synchronisation, this should be added to the pom:

    <pluginRepositories>
        <pluginRepository>
            <id>bintray.bsi.maven</id>
            <url>http://dl.bintray.com/bsi-business-systems-integration-ag/scout-eclipse-org/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

**Comment by padyx** [comment]
Thanks for the hint @jmini .
I've pushed it to Central and expect it to appear there  in the next couple of hours.

**Comment by jmini** [comment]
I can see version `3.0.3` on http://search.maven.org/
Thank you!

**Comment by jmini** [comment]
I have updated the readme with 5aa541314d3beba75e0d86e0339ea53d4682ff9e (I wanted to do it with a PR. I guess that for such a small change it is OK)
