### ISSUE TITLE
Dependency JAR is not fetched from custom repository

### ISSUE THREAD

**Issue by dts-ait** [BSI-Business-Systems-Integration-AG/eclipse-settings-maven-plugin#9]
I configured the eclipse-settings-maven-plugin to use a dependency that is hosted in maven central but on our custom repository that is added in the <repositories> section of the pom.xml.

```
<plugin>
	<groupId>org.eclipse.scout</groupId>
	<artifactId>eclipse-settings-maven-plugin</artifactId>
	<version>3.0.3</version>
	<dependencies>
		<!-- source for the .settings files -->
		<dependency>
			<groupId>at.ac.ait.dts</groupId>
			<artifactId>eclipse-settings</artifactId>
			<version>${eclipse.settings.version}</version>
		</dependency>
	</dependencies>
	<!-- specify which files are copied -->
	<configuration>
		<additionalConfig>
			<file>
				<name>.settings/org.eclipse.core.resources.prefs</name>
				<location>/org.eclipse.core.resources.prefs</location>
			</file>
			<file>
				<name>.settings/org.eclipse.jdt.core.prefs</name>
				<location>/org.eclipse.jdt.core.prefs</location>
			</file>
		</additionalConfig>
	</configuration>
</plugin>
```

If the dependency is not yet in my local repository (~/.m2) then I get the following error message when running `mvn org.eclipse.scout:eclipse-settings-maven-plugin:eclipse-settings` (also for non-SNAPSHOT versions)

> [ERROR] Failed to execute goal org.eclipse.scout:eclipse-settings-maven-plugin:3.0.3:eclipse-settings (default-cli) on project mped: Execution default-cli of goal org.eclipse.scout:eclipse-settings-maven-plugin:3.0.3:eclipse-settings failed: Plugin org.eclipse.scout:eclipse-settings-maven-plugin:3.0.3 or one of its dependencies could not be resolved: Could not find artifact at.ac.ait.dts:eclipse-settings:jar:1.0.0-SNAPSHOT

I "solved" the issue as follows:
```
<profiles>
	<profile>
		<id>eclipse-settings</id>
		<dependencies>
			<!-- Required for eclipse-settings plugin, otherwise it is not fetched 
				automatically -->
			<dependency>
				<groupId>at.ac.ait.dts</groupId>
				<artifactId>eclipse-settings</artifactId>
				<version>${eclipse.settings.version}</version>
			</dependency>
		</dependencies>
	</profile>
</profiles>
```

And then I run `mvn dependency:copy-dependencies org.eclipse.scout:eclipse-settings-maven-plugin:eclipse-settings -Peclipse-settings` instead of `mvn org.eclipse.scout:eclipse-settings-maven-plugin:eclipse-settings`. This automatically downloads the missing dependency and then the eclipse-settings-maven-plugin can work its magic.

However, the eclipse-settings-maven-plugin should imho download new dependencies on its own - even from custom repositories.

**Comment by dts-ait** [comment]
Thank you for the fast response! Our dependency resides in a Nexus hosted in our company and I add it via a `<repository>`. I was not aware of the `<pluginRepository>`, now it works perfectly! 

Maybe you want to add this as a hint to the documentation?

**Comment by jmini** [comment]
PR: https://github.com/BSI-Business-Systems-Integration-AG/eclipse-settings-maven-plugin/pull/10
